/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aaaa;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
    public static boolean search(ArrayList<Integer> array, Integer e,int f,int k) {
        System.out.println("inside search");
        if (array == null) return false;
  
        for (int elt : array) {
          if (elt == e || elt ==f ||elt ==k) return true;
        }
        return false;
      }



}
